Add check for code format in CI (#4)
- Add formatter to rebar3 and add a check in CI
- Format code to `erlang-mode` standard

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,6 +7,25 @@ on:
       - master
 
 jobs:
+  fmt:
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v3
+      - name: Prepare
+        run: |
+          sudo apt update
+          sudo apt install emacs-nox
+      - name: erlang-formatter
+        run: |
+          rebar3 fmt
+          status="$(git status --untracked-file=no --porcelain)"
+          if [ ! -z "$status" ]; \
+          then \
+             echo "Error: Please format the following files (e.g. run 'rebar3 fmt')"; \
+             echo "$status"; \
+             exit 1; \
+          fi
+
   build:
     runs-on: ubuntu-20.04
     steps:
